"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta# settings.py

# --- Windows: pointer automatiquement vers les DLL GDAL/GEOS/PROJ dans le venv ---
# if os.name == "nt":
#     VENV_BASE = os.environ.get("VIRTUAL_ENV")
#     if VENV_BASE:
#         OSGeo_DIR = os.path.join(VENV_BASE, "Lib", "site-packages", "osgeo")

#         # 1) PATH: pour que Python trouve les .dll
#         os.environ["PATH"] = OSGeo_DIR + os.pathsep + os.environ.get("PATH", "")

#         # 2) Données PROJ & GDAL (NE PAS concaténer PATH ici)
#         os.environ["PROJ_LIB"] = os.path.join(OSGeo_DIR, "data", "proj")
#         os.environ["GDAL_DATA"] = os.path.join(OSGeo_DIR, "data", "gdal")

#         # 3) Localiser les DLL réelles (ta wheel met "gdal.dll", pas gdal311.dll)
#         #    On cherche dynamiquement pour éviter les fautes de nommage.
#         gdal_candidates = glob.glob(os.path.join(OSGeo_DIR, "gdal*.dll"))
#         geos_candidates = (glob.glob(os.path.join(OSGeo_DIR, "geos_c*.dll")) +
#                            glob.glob(os.path.join(OSGeo_DIR, "libgeos_c*.dll")))

#         # Priorité à "gdal.dll" s'il existe
#         gdal_path = None
#         for p in gdal_candidates:
#             if os.path.basename(p).lower() == "gdal.dll":
#                 gdal_path = p
#                 break
#         if not gdal_path and gdal_candidates:
#             gdal_path = gdal_candidates[0]

#         geos_path = geos_candidates[0] if geos_candidates else None

#         # 4) Expose pour GeoDjango (si trouvés)
#         if geos_path:
#             GEOS_LIBRARY_PATH = geos_path  # Django le lit s’il est dans le module settings
#         if gdal_path:
#             GDAL_LIBRARY_PATH = gdal_path
      
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%x#0wa&djs3q9)pg*#_%+-3sb7_3p(#1lzs6hun+py+rtn&ej='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["localhost", "192.168.1.13", "127.0.0.1", "backend.decrouresi.com", "decrouresi.com"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Exemple pour React
    "http://192.168.1.12:5173",
    "http://192.168.1.13:5173",
    "https://backend.decrouresi.com",
    "https://decrouresi.com",
   
]
from corsheaders.defaults import default_headers  # ADDED

CORS_ALLOW_HEADERS = list(default_headers) + [    # ADDED
    'idempotency-key',                            # ADDED: notre header custom
]


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'rest_framework',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.gis',
    #'rest_framework_gis',
    'rest_framework_simplejwt',
    'userauths',
    'listings',
    'houses',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 'USER': 'c2738587c_Olivier',
# 'PASSWORD': 'L@QDe5az@ks36Di',

# DATABASES = {
#      'default': {
#         'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': 'babiresi',
#         'USER': 'postgres',
#         'PASSWORD': 'Olivier1207.',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }
# settings.py


DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'c2738587c_decrouresi',
        'USER': 'c2738587c_Olivier',
        'PASSWORD': 'Blandine1207.',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# DATABASES = {
#     "default": {
#         "ENGINE": "django.contrib.gis.db.backends.postgis",
#         "NAME": "decroure_principal",
#         "USER": "decroure",
#         "PASSWORD": "h63tIg42Vn",
#         "HOST": "uk17.acugis-dns.com",
#         "PORT": "5432",
#         "CONN_MAX_AGE": 60,  # connexion persistante (perf)
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR, 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOW_ALL_ORIGINS = True

AUTH_USER_MODEL = 'userauths.User'

CSRF_TRUSTED_ORIGINS = ['https://decrouresi.com']



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


PAYSTACK_SECRET_KEY = "sk_test_e645af35c48d9a0997a2a524919c34219268f5de"
PAYSTACK_BASE_URL = "https://api.paystack.co"
PAYSTACK_PUBLIC_KEY = "pk_test_8a9eca8b554bb106bdd36dbc0d04b1a8cd9aa6b6"
PAYSTACK_CALLBACK_URL = "https://decrouresi.com/payments/paystack/return"

VAPID_PRIVATE_KEY = "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgB1OOxe3aZrgXU4BKF-uODpxfhuLY1XRoDnAGVZ4q-7uhRANCAAR6pEfDwcwYzIY7sYtdHfPLDLGb7JRZfamuu9ZyRmNN6zK-zj7MTxxH2cK_JrANaFKMYa1D1CsE0yBFnoD8Uq9L"
VAPID_PUBLIC_KEY = "BHqkR8PBzBjMhjuxi10d88sMsZvslFl9qa671nJGY03rMr7OPsxPHEfZwr8msA1oUoxhrUPUKwTTIEWegPxSr0s"
VAPID_CLAIMS = {"sub": "mailto:kangaholivier58@gmail.com"}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
  "PAGE_SIZE": 24,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=50),
    'ROTATE_REFRESH_TOKEN': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',

    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES' : ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
  

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1)
}
