# Generated by Django 6.0.1 on 2026-05-19 03:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('excursion', 'Excursion'), ('cours_cuisine', 'Cours de cuisine'), ('culturel', 'Visite culturelle'), ('nature', 'Nature & Randonnée'), ('plage', 'Plage & Eau'), ('nocturne', 'Vie nocturne'), ('artisanat', 'Atelier artisanat'), ('sport', 'Sport & Aventure')], default='excursion', max_length=20)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('price_per_person', models.PositiveIntegerField(default=0)),
                ('min_persons', models.PositiveIntegerField(default=1)),
                ('max_persons', models.PositiveIntegerField(default=20)),
                ('included_services', models.JSONField(blank=True, default=list)),
                ('meeting_point', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/activities/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='destinations.destination')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nb_persons', models.PositiveIntegerField(default=1)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=15)),
                ('client_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.activity')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('craft_type', models.CharField(choices=[('pagne', 'Pagne & Tissu'), ('sculpture', 'Sculpture'), ('bijou', 'Bijouterie'), ('poterie', 'Poterie'), ('vannerie', 'Vannerie'), ('peinture', 'Peinture'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/artisans/')),
                ('video_intro_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('made_in_ci_badge', models.BooleanField(default=False)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artisans', to='destinations.destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtisanBoxSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.JSONField(default=dict)),
                ('delivery_country', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause'), ('cancelled', 'Annulé')], default='active', max_length=15)),
                ('price_monthly_eur', models.PositiveIntegerField(default=35)),
                ('next_shipment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artisan_box_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('languages', models.JSONField(default=list)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/drivers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinations_covered', models.ManyToManyField(blank=True, related_name='drivers', to='destinations.destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/guides/')),
                ('video_intro_url', models.URLField(blank=True)),
                ('specialties', models.JSONField(default=list)),
                ('languages', models.JSONField(default=list)),
                ('half_day_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('full_day_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('multi_day_price', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_anglophone_certified', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_bookings', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinations', models.ManyToManyField(blank=True, related_name='guides', to='destinations.destination')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='services.guide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('half_day', 'Demi-journée'), ('full_day', 'Journée'), ('multi_day', 'Multi-jours')], default='full_day', max_length=15)),
                ('nb_days', models.PositiveIntegerField(default=1)),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=15)),
                ('client_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_bookings', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_bookings', to='destinations.destination')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.guide')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('price_fcfa', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(blank=True, null=True)),
                ('made_to_order', models.BooleanField(default=False)),
                ('production_time_days', models.PositiveIntegerField(default=7)),
                ('category', models.CharField(choices=[('pagne', 'Pagne & Tissu'), ('sculpture', 'Sculpture'), ('bijou', 'Bijouterie'), ('poterie', 'Poterie'), ('vannerie', 'Vannerie'), ('peinture', 'Peinture'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.artisan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/products/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.product')),
            ],
            options={
                'ordering': ['-is_cover', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_type', models.CharField(choices=[('local_abidjan', 'Local Abidjan'), ('national', 'National CI'), ('international', 'International')], default='local_abidjan', max_length=20)),
                ('delivery_address', models.JSONField(default=dict)),
                ('total_fcfa', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('in_production', 'En production'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='services.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(choices=[('maquis', 'Maquis'), ('restaurant', 'Restaurant'), ('street_food', 'Street Food'), ('gastronomique', 'Gastronomique'), ('cafe', 'Café / Snack')], default='maquis', max_length=20)),
                ('price_range', models.CharField(choices=[('€', 'Économique'), ('€€', 'Moyen'), ('€€€', 'Gastronomique')], default='€', max_length=5)),
                ('opening_hours', models.CharField(blank=True, max_length=200)),
                ('signature_dishes', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='services/restaurants/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to='destinations.destination')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating_avg'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/restaurants/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.restaurant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('object_type', models.CharField(choices=[('listing', 'Logement'), ('guide', 'Guide'), ('activity', 'Activité'), ('driver', 'Chauffeur'), ('restaurant', 'Restaurant'), ('artisan', 'Artisan'), ('consultant', 'Conseiller voyage'), ('agency', 'Agence voyage')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('citadine', 'Citadine'), ('berline', 'Berline'), ('suv', 'SUV'), ('minibus', 'Minibus (6+ pers.)'), ('4x4', '4x4')], default='berline', max_length=15)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='services/vehicles/')),
                ('price_per_day_with_driver', models.PositiveIntegerField(default=0)),
                ('price_per_day_without_driver', models.PositiveIntegerField(default=0)),
                ('has_ac', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='services.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_driver', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pickup_location', models.CharField(blank=True, max_length=255)),
                ('dropoff_location', models.CharField(blank=True, max_length=255)),
                ('total_days', models.PositiveIntegerField(default=1)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=15)),
                ('client_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='services.vehicle')),
            ],
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['destination', 'category'], name='services_ac_destina_ee163c_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_verified', 'is_active'], name='services_ac_is_veri_c72efa_idx'),
        ),
        migrations.AddIndex(
            model_name='activitybooking',
            index=models.Index(fields=['activity', 'date'], name='services_ac_activit_54f47c_idx'),
        ),
        migrations.AddIndex(
            model_name='activitybooking',
            index=models.Index(fields=['client', 'status'], name='services_ac_client__bd6b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['is_verified', 'craft_type'], name='services_ar_is_veri_665ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='artisanboxsubscription',
            index=models.Index(fields=['status', 'next_shipment_date'], name='services_ar_status_5cd0f2_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_verified', 'is_available'], name='services_dr_is_veri_aa03a0_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['is_verified', 'is_available'], name='services_gu_is_veri_93155c_idx'),
        ),
        migrations.AddIndex(
            model_name='guideavailability',
            index=models.Index(fields=['guide', 'date'], name='services_gu_guide_i_44e188_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guideavailability',
            unique_together={('guide', 'date')},
        ),
        migrations.AddIndex(
            model_name='guidebooking',
            index=models.Index(fields=['guide', 'date'], name='services_gu_guide_i_2f8eab_idx'),
        ),
        migrations.AddIndex(
            model_name='guidebooking',
            index=models.Index(fields=['client', 'status'], name='services_gu_client__c5fd29_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['artisan', 'is_available'], name='services_pr_artisan_2ee381_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='services_pr_categor_867e35_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['buyer', 'status'], name='services_pr_buyer_i_09aafc_idx'),
        ),
        migrations.AddIndex(
            model_name='productorder',
            index=models.Index(fields=['product', 'status'], name='services_pr_product_1e9a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['destination', 'category'], name='services_re_destina_f876d7_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_verified', 'is_active'], name='services_re_is_veri_de6359_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['object_type', 'object_id'], name='services_re_object__a44600_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['author', 'object_type'], name='services_re_author__bc7ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['driver', 'is_available'], name='services_ve_driver__f25298_idx'),
        ),
        migrations.AddIndex(
            model_name='driverbooking',
            index=models.Index(fields=['vehicle', 'start_date'], name='services_dr_vehicle_cf4a06_idx'),
        ),
        migrations.AddIndex(
            model_name='driverbooking',
            index=models.Index(fields=['client', 'status'], name='services_dr_client__73cbc9_idx'),
        ),
    ]
