# Generated by Django 6.0.1 on 2026-05-28 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='artisan',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['latitude', 'longitude'], name='services_ac_latitud_a91682_idx'),
        ),
        migrations.AddIndex(
            model_name='artisan',
            index=models.Index(fields=['latitude', 'longitude'], name='services_ar_latitud_692831_idx'),
        ),
        migrations.AddIndex(
            model_name='guide',
            index=models.Index(fields=['latitude', 'longitude'], name='services_gu_latitud_638e9d_idx'),
        ),
    ]
