# Generated by Django 6.0.1 on 2026-05-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('region', models.CharField(blank=True, choices=[('abidjan', 'Abidjan'), ('bas_sassandra', 'Bas-Sassandra'), ('comoe', 'Comoé'), ('denguele', 'Denguélé'), ('goh_djiboua', 'Gôh-Djiboua'), ('lacs', 'Lacs'), ('lagunes', 'Lagunes'), ('marahoue', 'Marahoué'), ('montagnes', 'Montagnes'), ('savanes', 'Savanes'), ('vallee_du_bandama', 'Vallée du Bandama'), ('woroba', 'Woroba'), ('yamoussoukro', 'Yamoussoukro'), ('zanzan', 'Zanzan')], max_length=80)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='destinations/covers/')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('practical_info', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['is_published', 'is_featured'], name='destination_is_publ_f3d652_idx'), models.Index(fields=['region'], name='destination_region_ebb36c_idx'), models.Index(fields=['slug'], name='destination_slug_528bb8_idx')],
            },
        ),
    ]
