# Generated by Django 6.0.1 on 2026-01-15 17:34

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('area', models.CharField(blank=True, max_length=20, null=True)),
                ('borough', models.CharField(blank=True, max_length=80, null=True)),
                ('address_label', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('listing_type', models.CharField(choices=[('studio', 'Studio'), ('appartement', 'Appartement'), ('maison', 'Maison'), ('villa', 'Villa'), ('chambre', 'Chambre')], default='appartement', max_length=20)),
                ('price_per_night', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_guests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_hot_water', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('guests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée')], default='pending', max_length=15)),
                ('price_per_night', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active', 'city'], name='listings_li_is_acti_0bda1a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['area', 'borough'], name='listings_li_area_d2f619_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_per_night'], name='listings_li_price_p_278f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'start_date', 'end_date'], name='listings_bo_listing_8c812a_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='listings_bo_user_id_f12e91_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='booking_valid_range'),
        ),
    ]
