# Generated by Django 6.0.1 on 2026-02-02 11:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('borough', models.CharField(blank=True, max_length=80, null=True)),
                ('address_label', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('listing_type', models.CharField(choices=[('studio', 'Studio'), ('appartement', 'Appartement'), ('maison', 'Maison'), ('villa', 'Villa'), ('chambre', 'Chambre')], default='appartement', max_length=20)),
                ('price_per_night', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_guests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('bedrooms', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bathrooms', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('living_rooms', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('kitchens', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('beds', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('test', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_hot_water', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_generator', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allows_smoking', models.BooleanField(default=False)),
                ('allows_pets', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('desired_start_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('guests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('requested', 'Demande envoyée (en attente gérant)'), ('rejected', 'Refusée (déjà pris / indisponible)'), ('approved', 'Acceptée (client peut payer)'), ('awaiting_payment', 'En attente de paiement'), ('paid', 'Acompte payé (escrow plateforme)'), ('checked_in', 'Client arrivé (code validé)'), ('released', 'Reversement effectué (admin)'), ('cancelled', 'Annulée'), ('expired', 'Expirée')], default='requested', max_length=20)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('owner_note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('price_per_night', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('deposit_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('platform_commission', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('paystack_fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_to_pay', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('escrow_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('key_code_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('key_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('key_code', models.CharField(blank=True, max_length=6, null=True)),
                ('payout_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('payout_status', models.CharField(choices=[('unpaid', 'Non payé'), ('paid', 'Payé')], default='unpaid', max_length=10)),
                ('payout_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['is_cover', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=20)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiée'), ('success', 'Réussie'), ('failed', 'Échouée')], default='initiated', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('raw', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='listings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDateProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=180, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_proposals', to='listings.booking')),
            ],
            options={
                'indexes': [models.Index(fields=['booking', 'start_date', 'end_date'], name='listings_bo_booking_b694f7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_active', 'city'], name='listings_li_is_acti_0bda1a_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['area', 'borough'], name='listings_li_area_d2f619_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price_per_night'], name='listings_li_price_p_278f5d_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['listing', 'status'], name='listings_bo_listing_f09998_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='listings_bo_user_id_f12e91_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'created_at'], name='listings_bo_status_5903d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='booking_valid_range_if_dates_set'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'is_cover'], name='listings_li_listing_7c3dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'order'], name='listings_li_listing_5fba7f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider', 'reference'], name='listings_pa_provide_1ebd13_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['booking', 'status'], name='listings_pa_booking_91e83f_idx'),
        ),
        migrations.AddIndex(
            model_name='pushsubscription',
            index=models.Index(fields=['user', 'created_at'], name='listings_pu_user_id_fce448_idx'),
        ),
    ]
