# Generated by Django 6.0.1 on 2026-01-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_bookingdateproposal_paymenttransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='key_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
