# Generated by Django 6.0.1 on 2026-01-21 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_booking_key_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='allows_pets',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='allows_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='kitchens',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listing',
            name='living_rooms',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
