# Generated by Django 6.0.1 on 2026-05-19 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveBigIntegerField(default=0)),
                ('available_points', models.PositiveBigIntegerField(default=0)),
                ('withdrawn_points', models.PositiveBigIntegerField(default=0)),
                ('level', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VlogChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('theme', models.CharField(max_length=100)),
                ('prize_amount_fcfa', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='vlogs/challenges/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='VlogSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='vlogs/series_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('cloudinary_url', models.URLField(blank=True, max_length=500)),
                ('cloudinary_public_id', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('gastronomie', 'Gastronomie'), ('culture', 'Culture & Traditions'), ('nature', 'Nature & Paysages'), ('artisanat', 'Artisanat'), ('fetes', 'Fêtes & Événements'), ('vie_locale', 'Vie quotidienne'), ('plages', 'Plages'), ('architecture', 'Architecture & Histoire'), ('aventure', 'Aventure')], default='vie_locale', max_length=30)),
                ('ambiance', models.CharField(blank=True, choices=[('aventure', 'Aventure'), ('detente', 'Détente'), ('culturel', 'Découverte culturelle'), ('famille', 'Family-friendly'), ('romantique', 'Romantique'), ('nocturne', 'Vie nocturne')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('saves_count', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlogs', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlogs', to='destinations.destination')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='vlogs.vlogseries')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('watch_percentage', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vlog_views', to=settings.AUTH_USER_MODEL)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='vlogs.vlog')),
            ],
        ),
        migrations.CreateModel(
            name='PointWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_points', models.PositiveIntegerField()),
                ('amount_fcfa', models.PositiveIntegerField()),
                ('method', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('paystack', 'Paystack')], max_length=20)),
                ('phone_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('rejected', 'Rejeté')], default='pending', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='vlogs_point_user_id_ee64ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('view', 'Vue'), ('like', 'Like reçu'), ('comment', 'Commentaire reçu'), ('share', 'Partage'), ('save', 'Sauvegarde'), ('booking_generated', 'Réservation générée'), ('artisan_order', 'Commande artisan générée'), ('featured', 'Vlog mis en avant'), ('challenge_win', 'Victoire challenge'), ('withdrawal', 'Retrait')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
                ('source_vlog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlogs.vlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='vlogs_point_user_id_c7c3b7_idx'), models.Index(fields=['type', 'created_at'], name='vlogs_point_type_383d40_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChallengeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_entries', to=settings.AUTH_USER_MODEL)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_entries', to='vlogs.vlog')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='vlogs.vlogchallenge')),
            ],
            options={
                'indexes': [models.Index(fields=['challenge', 'created_at'], name='vlogs_chall_challen_33a597_idx')],
                'unique_together': {('user', 'challenge')},
            },
        ),
        migrations.CreateModel(
            name='VlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vlogs.vlogcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_comments', to=settings.AUTH_USER_MODEL)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vlogs.vlog')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['vlog', 'created_at'], name='vlogs_vlogc_vlog_id_a54d0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='VlogLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_likes', to=settings.AUTH_USER_MODEL)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='vlogs.vlog')),
            ],
            options={
                'indexes': [models.Index(fields=['vlog', 'created_at'], name='vlogs_vlogl_vlog_id_17d710_idx')],
                'unique_together': {('user', 'vlog')},
            },
        ),
        migrations.CreateModel(
            name='VlogSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlog_saves', to=settings.AUTH_USER_MODEL)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='vlogs.vlog')),
            ],
            options={
                'unique_together': {('user', 'vlog')},
            },
        ),
        migrations.AddIndex(
            model_name='vlog',
            index=models.Index(fields=['is_published', 'is_featured'], name='vlogs_vlog_is_publ_dadb4f_idx'),
        ),
        migrations.AddIndex(
            model_name='vlog',
            index=models.Index(fields=['author', 'created_at'], name='vlogs_vlog_author__d99fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='vlog',
            index=models.Index(fields=['region', 'category'], name='vlogs_vlog_region_5f0b74_idx'),
        ),
        migrations.AddIndex(
            model_name='vlog',
            index=models.Index(fields=['destination'], name='vlogs_vlog_destina_6699f1_idx'),
        ),
        migrations.AddIndex(
            model_name='vlogview',
            index=models.Index(fields=['vlog', 'created_at'], name='vlogs_vlogv_vlog_id_a5a100_idx'),
        ),
        migrations.AddIndex(
            model_name='vlogview',
            index=models.Index(fields=['user', 'vlog'], name='vlogs_vlogv_user_id_fcaaa2_idx'),
        ),
    ]
